name: notification

on:
  schedule:
    - cron: '0 * * * *' # Every hour
  workflow_dispatch:

jobs:
  cleanup-notifications:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true

      - name: Run cleanup
        env:
          GITHUB_TOKEN: ${{ secrets.CLEANUP_TOKEN }}
        run: go run cleanup-notifications.go --no-dry-run
