name: notification

on:
  schedule:
    - cron: '0 * * * *' # Every hour
  workflow_dispatch:

jobs:
  cleanup-notifications:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: cleanup-notifications
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.CLEANUP_TOKEN }}
          script: |
            const script = require('./cleanup-notifications.js')
            script({github, context})
